### PR TITLE
[0.1.0]Breaking changes: Reactoring models Part 1

### PR DESCRIPTION
**Pull request by Wh1isper**
## Motivation and Context

- Intro `DiscreteInspector` for `CTGAN`, which useful for guessing discrete columns
- `Metadata` support(vanilla version for now)
- Drop BSL packages, use their MIT Lincensed code

## Types of changes

- [ ] Maintenance (no change in code, maintain the project's CI, docs, etc.)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Wh1isper** [comment]
Due to sdv-dev changed their license to BSL License, we copy their MIT licensed code into sdgx/models/components/sdv_*

**Comment by Wh1isper** [comment]
@MooooCat 

In the second part, I will replace the current `CTGAN` implementation with our custom `SynthesizerModel`. This will achieve the basic functionality of version 0.1.0(as an library). And it will be the first preview version.

After this, I hope we can port the performance optimisations and compatibility modifications that we did before. A series of documentation updates and development of CLI tools will also be needed.

**Comment by Wh1isper** [comment]
For the sake of review, I've split the PR into two parts, the first being the Inspector and Metadata changes, and the other being the BSL Licence changes.

@MooooCat If there are no problems, I will first merge the second part into the `0.1.0-refactoring-model` branch: https://github.com/hitsz-ids/synthetic-data-generator/pull/69 and merge this pr into main after passing the CI.

**Comment by MooooCat** [comment]
> For the sake of review, I've split the PR into two parts, the first being the Inspector and Metadata changes, and the other being the BSL Licence changes.
> 
> @MooooCat If there are no problems, I will first merge the second part into the `0.1.0-refactoring-model` branch: #69 and merge this pr into main after passing the CI.

Cool, some algorithm-related branches in development may also synchronize the latest components.

**Review by MooooCat — APPROVED** [review]

**Pull request merged**
