### PR TITLE
Feature metric jsd

### LINKED ISSUE #40: [Feature]🌌Jensen–Shannon divergence Implementation
### 🚅Search before asking

I have searched for issues similar to this one.

### 🚅Description

In probability theory and statistics, the [Jensen–Shannon divergence](https://en.wikipedia.org/wiki/Jensen–Shannon_divergence), “JS散度” in Chinese, is a method of measuring the similarity between two probability distributions. It is also known as information radius (IRad) or total divergence to the average. It is based on the Kullback–Leibler divergence, with some notable (and useful) differences, including that it is symmetric and it always has a finite value. The square root of the Jensen–Shannon divergence is a metric often referred to as Jensen–Shannon distance.

The value range of JSD is [0,1], when two distributions are similar, JSD approaches 0. If the two distributions do not overlap at all, JSD is equal to the constant 1. The closer the JSD to 0, the more similar the distribution, thus the higher the quality of the synthetic data.

### 🏕Solution

Implement the calculation of Jensen–Shannon divergence by coding or calling methods in existing modules. The implementation code should be located in the `sdgx/metrics` directory, and the class implementation should inherit from the base class in `sdgx/metrics/base.py`.

### 🍰Detail

In addition to implementing JSD, the demo code in `example/` and the related code in `Readme.md` should also be added.

Since this is the first metric method implemented, the base class can be modified if necessary to make it more suitable for various metric calculations.

### PR DESCRIPTION
**Pull request by sjh120**
## Description

JSD实现
## Motivation and Context

Resolves #40 

## How has this been tested?

通过修改1_ctgan_example.py中selected_columns字段选择要选取的列，isDiscrete字段表示是否选取离散列或连续列，将计算多列联合概率密度的JS散度
## Types of changes

- [ ] Maintenance (no change in code, maintain the project's CI, docs, etc.)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by Wh1isper — CHANGES_REQUESTED** [review]
Please remove all .idea/* files, you can add `.idea/` in root's `.gitignore`

**Comment by MooooCat** [comment]
@sjh120  Please sync the base class currently in branch "feature-metric-base".

This PR should only contains the following files：

- example/1_ctgan_example.py
- sdgx/metrics/column/jsd.py

**Comment by sjh120** [comment]
已修改，对base.py的修改为直接pull base class in branch "feature-metric-base"的结果

**Review by Wh1isper — APPROVED** [review]
LGTM, as a demo.

But it's probably not a good idea to directly modify an existing example...

What do you think?  @MooooCat

**Pull request merged**
