### PR TITLE
Add base model for multi-table statistic model, change single-table base class location

### PR DESCRIPTION
**Pull request by MooooCat**
## Description

- Add base model for multi-table statistic model.
- Change single-table base class location.
- Change check settings in metadata.

## Motivation and Context

The main purpose of this change is to adapt to multi-table synthetic data scenarios

## How has this been tested?

A test case has been provided for the method of base class.

## Types of changes

- [ ] Maintenance (no change in code, maintain the project's CI, docs, etc.)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Wh1isper** [comment]
Nice PR, and I have a couple questions:
- Why does `MultiTableSynthesizerModel` inherit from `pydantic.BaseModel`, given that he doesn't seem to be a data object.
- If you want to accept streaming files(`DataLoader`) or `Dataframe` for evaluation, you only need to define the two mutually exclusive parameters `raw_data` and `dataloader` in the kwargs, what is the importance of the enum class `DataAccessType`?
	- Also, if the `raw_data` parameter needs to be added, one might want to consider how the existing architecture extends this parameter

**Comment by MooooCat** [comment]
> * Why does `MultiTableSynthesizerModel` inherit from `pydantic.BaseModel`, given that he doesn't seem to be a data object.

Regarding this question, it mainly comes from my lack of understanding of `pydantic.BaseModel`. Before that, I thought it was just a base class convenient for developer to implement. After checking, I found that:

> "Pydantic is the most widely used data validation library for Python. ”

this is indeed inconsistent with the purpose of a statistical model.

**Comment by Z712023** [comment]
Offer fuel on snowy weather! Multi-table model is what we want!

**Review by Z712023 — COMMENTED** [review]
The validation in metadata is ok!

**Comment by MooooCat** [comment]
> Offer fuel on snowy weather! Multi-table model is what we want!

There will be some minor modifications before merge.

**Comment by MooooCat** [comment]
> * Why does `MultiTableSynthesizerModel` inherit from `pydantic.BaseModel`, given that he doesn't seem to be a data object.
> * If you want to accept streaming files(`DataLoader`) or `Dataframe` for evaluation, you only need to define the two mutually exclusive parameters `raw_data` and `dataloader` in the kwargs, what is the importance of the enum class `DataAccessType`?  
>   * Also, if the `raw_data` parameter needs to be added, one might want to consider how the existing architecture extends this parameter

I removed the `pydantic.BaseModel`, and use `sdgx.models.base.SynthesizerModel` instead. 

I removed the `DataAccessType` and set two mutually exclusive parameters `use_raw_data` and `use_dataloader` in `sdgx.models.base.SynthesizerModel`, this base class will be inherit by all ML and statistic models. 

In existing architecture, I think it's OK to simply set `use_raw_data` to True or `use_dataloader` to True. 

In the future, we can add support for these two data access methods . (I leave this to future, not in this PR).

Currently, this modification does not affect the use of existing models.

**Review by Wh1isper — APPROVED** [review]
I prefer to merge it now and make further improvements in the implementation of multi-table simulations.

**Pull request merged**
