### PR TITLE
Add demo data for multi-table scenario

### PR DESCRIPTION
**Pull request by MooooCat**
## Types of changes

- [ ] Maintenance (no change in code, maintain the project's CI, docs, etc.)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MooooCat** [comment]
At present, the code of demo data is located in utils.py. I found that importing metadata in the implementation of utils.py will lead to circular import.

I recommend moving these implementations to a new file, such as dataset/demo.py, to make the functions of each module more clear.

What do you think of this solution? @Wh1isper

**Comment by Wh1isper** [comment]
Moving demo `Metadata` into a single file will be better. This represents the user's preprocessing, not our utils.

**Comment by MooooCat** [comment]
> Moving demo `Metadata` into a single file will be better. This represents the user's preprocessing, not our utils.

It makes sense, building metadata belongs to user process.

The function `get_demo_multi_table` will return a DataFrame like `get_demo_single_table`, without Metadata.

**Review by Wh1isper — APPROVED** [review]
LGTM, thanks

**Pull request merged**
