### PR TITLE
[0.1.0] Intro NDArryLoader

### PR DESCRIPTION
**Pull request by Wh1isper**
## Motivation and Context

- Introduce the `NDArrayLoader` for lazy reading of columnarly stored ndarry
- Update docstring and examples

## Types of changes

- [ ] Maintenance (no change in code, maintain the project's CI, docs, etc.)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Wh1isper** [comment]
@MooooCat 
Please review the code first, I'm adding documentation.

**Comment by MooooCat** [comment]
> @MooooCat Please review the code first, I'm adding documentation.

Sure.

**Review by MooooCat — APPROVED** [review]

**Comment by Wh1isper** [comment]
Will update user guide before official release

**Comment by MooooCat** [comment]
I have a question about the NDArray Loader.

 I noticed that it names the .npy in order. 

(I'm not sure if this will happen yet) When multiple data loaders run at the same time using default parameters (that is, the same cache_dir), this sequential naming method may cause conflicts:

NDArrayLoader 1 stores `1.npy` ，then NDArrayLoader 2 store another Array on same ndarry_cache dir.

In the naming of cached .npy files, if the path contains an id field, there will be no such concern. Also, suggesting developers to use different cache paths is obviously a right approach.

Could this be a problem?

**Comment by Wh1isper** [comment]
@MooooCat Yes, different NDArrayLoader should use different subdirs. I'll draft a PR fot it

**Pull request merged**
