### PR TITLE
pull: Support NPZ format in current transformer

### PR DESCRIPTION
**Pull request by sirisneupane123**
## Types of changes

- [ ] Maintenance (no change in code, maintain the project's CI, docs, etc.)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MooooCat** [comment]
@sirisneupane123 @sam3179  Thank you for the PR.

We'll also do some code review later.

Viewing from the current code structure, demo.py should be moved to the example/ directory (and renamed), and test should be added to the existing unit tests in the tests/ directory.

**Comment by Wh1isper** [comment]
Why is there a test case in sdgx/models/components/sdv_ctgan/data_transformer_test.py and it's using unittest's style

Is there any reason not to put it under tests, as well as not using pytest?

**Comment by MooooCat** [comment]
The current file structure of this PR is **incorrect**.  @sam3179 

Unit tests should be located in the `tests/models` directory and tested using pytest.

**Comment by MooooCat** [comment]
> Why is there a test case in sdgx/models/components/sdv_ctgan/data_transformer_test.py and it's using unittest's style
> 
> Is there any reason not to put it under tests, as well as not using pytest?

@Wh1isper Is it possible that these three accounts are controlled by a generative AI that is being tested?

**Comment by Wh1isper** [comment]
Haha, then they have a long way to go

**Comment by jalr4ever** [comment]
@MooooCat Is there any update on this PR? I noticed there are quite a few issues in the code that haven't been fixed yet.

**Comment by MooooCat** [comment]
This PR does not meet the requirements, I will close it.

**Pull request closed without merging**
